name: tests
on:
  pull_request:
    branches: [master]

jobs:
  on-pr-from-branch:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: Test PR from branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install prettier

      - name: Check style
        run: |
          autoflake . --remove-all-unused-imports --quiet --in-place -r --exclude venv --check
          black . --check
          isort . --check --profile black
          npx prettier --check .

      - name: Add service account so tests work
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: Test main
        run: python main_test.py

      - name: Send email to Connor and Anmol
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: epschedule@hotmail.com
          password: ${{secrets.EPHMAIL_PASSWORD}}
          subject: Github Pull Request Submitted
          to: cwest@eastsideprep.org,ajosan@eastsideprep.org
          from: EPSchedule
          body: Pull request submitted. Please review at https://github.com/EastsidePreparatorySchool/epschedule/pulls
          ignore_cert: true
          convert_markdown: true
          priority: low
          nodemailerlog: false
          nodemailerdebug: false

  on-pr-from-fork:
    if: github.event.pull_request.head.repo.full_name != github.repository
    name: Test PR from fork
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install prettier

      - name: Check style
        run: |
          autoflake . --remove-all-unused-imports --quiet --in-place -r --exclude venv --check
          black . --check
          isort . --check --profile black
          npx prettier --check .
      - name: Send email to Connor and Anmol
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.office365.com
          server_port: 587
          secure: true
          username: epschedule@hotmail.com
          password: ${{secrets.EPHMAIL_PASSWORD}}
          subject: Github Pull Request Submitted
          to: cwest@eastsideprep.org,ajosan@eastsideprep.org
          from: EPSchedule
          body: Pull request submitted. Please review at https://github.com/EastsidePreparatorySchool/epschedule/pulls
          ignore_cert: true
          convert_markdown: true
          priority: low
          nodemailerlog: false
          nodemailerdebug: false
